baseURL = "https://industrial-sbc.com/"
title = "Industrial sbc"
languageCode = "en-us"

enableRobotsTXT = true
disableKinds = ["RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home     = ["HTML"]        
  section  = ["HTML"]
  taxonomy = ["HTML"]         
  term     = ["HTML"]     

[pagination]
  pagerSize = 10

# sitemap 配置
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true